name: meiso
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  flutter_riverpod: ^2.4.4
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  package_info: ^2.0.2
  cloud_firestore: ^4.11.0
  hooks_riverpod: ^2.4.4
  flutter_hooks: ^0.20.3
  google_fonts: ^6.1.0
  flutter_localization: ^0.2.0
  gap: ^3.0.1
  url_launcher: ^6.1.14
  hexcolor: ^3.0.1
  syncfusion_flutter_charts: ^23.1.44
  intl: any
  flutter_overboard: ^3.1.1
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.13.1
  json_annotation: ^4.8.1
  animated_checkmark: ^2.0.0
  flutter_native_splash: ^2.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true
